[project]
name = "sublex"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "lupa>=2.5",
    "maturin>=1.9.0",
    "pyyaml==6.0.2",
    "requests>=2.32.4",
]
